# Copyright (C) 2017-2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


PRODUCT_COPY_FILES += \
    vendor/amitwh/common/system/media/audio/ui/camera_click.ogg:system/media/audio/ui/camera_click.ogg \
	vendor/amitwh/common/system/media/audio/ui/VolumeIncremental.ogg:system/media/audio/ui/VolumeIncremental.ogg \
	vendor/amitwh/common/system/media/audio/ui/MessageSending.ogg:system/media/audio/ui/MessageSending.ogg \
	vendor/amitwh/common/system/media/audio/ui/KeypressStandard.ogg:system/media/audio/ui/KeypressStandard.ogg \
	vendor/amitwh/common/system/media/audio/ui/SystemTurnOff.ogg:system/media/audio/ui/SystemTurnOff.ogg \
	vendor/amitwh/common/system/media/audio/ui/Dock.ogg:system/media/audio/ui/Dock.ogg \
	vendor/amitwh/common/system/media/audio/ui/LowBattery.ogg:system/media/audio/ui/LowBattery.ogg \
	vendor/amitwh/common/system/media/audio/ui/Lock.ogg:system/media/audio/ui/Lock.ogg \
	vendor/amitwh/common/system/media/audio/ui/HeiHei.mp3:system/media/audio/ui/HeiHei.mp3 \
	vendor/amitwh/common/system/media/audio/ui/lock.ogg:system/media/audio/ui/lock.ogg \
	vendor/amitwh/common/system/media/audio/ui/KeypressInvalid.ogg:system/media/audio/ui/KeypressInvalid.ogg \
	vendor/amitwh/common/system/media/audio/ui/NFCTransferInitiated.ogg:system/media/audio/ui/NFCTransferInitiated.ogg \
	vendor/amitwh/common/system/media/audio/ui/BatteryPlugged_48k.ogg:system/media/audio/ui/BatteryPlugged_48k.ogg \
	vendor/amitwh/common/system/media/audio/ui/NumberPickerValueChange.ogg:system/media/audio/ui/NumberPickerValueChange.ogg \
	vendor/amitwh/common/system/media/audio/ui/VideoStop.ogg:system/media/audio/ui/VideoStop.ogg \
	vendor/amitwh/common/system/media/audio/ui/SystemDelete.ogg:system/media/audio/ui/SystemDelete.ogg \
	vendor/amitwh/common/system/media/audio/ui/Camera_click.ogg:system/media/audio/ui/Camera_click.ogg \
	vendor/amitwh/common/system/media/audio/ui/GoodBattery.ogg:system/media/audio/ui/GoodBattery.ogg \
	vendor/amitwh/common/system/media/audio/ui/NFCSuccess.ogg:system/media/audio/ui/NFCSuccess.ogg \
	vendor/amitwh/common/system/media/audio/ui/SystemError.ogg:system/media/audio/ui/SystemError.ogg \
	vendor/amitwh/common/system/media/audio/ui/VideoRecord.ogg:system/media/audio/ui/VideoRecord.ogg \
	vendor/amitwh/common/system/media/audio/ui/Effect_Tick.ogg:system/media/audio/ui/Effect_Tick.ogg \
	vendor/amitwh/common/system/media/audio/ui/MessageIncoming.ogg:system/media/audio/ui/MessageIncoming.ogg \
	vendor/amitwh/common/system/media/audio/ui/Unlock.ogg:system/media/audio/ui/Unlock.ogg \
	vendor/amitwh/common/system/media/audio/ui/KeypressDelete.ogg:system/media/audio/ui/KeypressDelete.ogg \
	vendor/amitwh/common/system/media/audio/ui/NFCInitiated.ogg:system/media/audio/ui/NFCInitiated.ogg \
	vendor/amitwh/common/system/media/audio/ui/InCallNotification.ogg:system/media/audio/ui/InCallNotification.ogg \
	vendor/amitwh/common/system/media/audio/ui/WirelessChargingStarted.ogg:system/media/audio/ui/WirelessChargingStarted.ogg \
	vendor/amitwh/common/system/media/audio/ui/MessageSendOut.ogg:system/media/audio/ui/MessageSendOut.ogg \
	vendor/amitwh/common/system/media/audio/ui/audio_end.ogg:system/media/audio/ui/audio_end.ogg \
	vendor/amitwh/common/system/media/audio/ui/BatteryPlugged.ogg:system/media/audio/ui/BatteryPlugged.ogg \
	vendor/amitwh/common/system/media/audio/ui/Media_Volume.ogg:system/media/audio/ui/Media_Volume.ogg \
	vendor/amitwh/common/system/media/audio/ui/audio_initiate.ogg:system/media/audio/ui/audio_initiate.ogg \
	vendor/amitwh/common/system/media/audio/ui/MusicShake.ogg:system/media/audio/ui/MusicShake.ogg \
	vendor/amitwh/common/system/media/audio/ui/KeypressReturn.ogg:system/media/audio/ui/KeypressReturn.ogg \
	vendor/amitwh/common/system/media/audio/ui/Camera_focus.ogg:system/media/audio/ui/Camera_focus.ogg \
	vendor/amitwh/common/system/media/audio/ui/Trusted.ogg:system/media/audio/ui/Trusted.ogg \
	vendor/amitwh/common/system/media/audio/ui/MessageComplete.ogg:system/media/audio/ui/MessageComplete.ogg \
	vendor/amitwh/common/system/media/audio/ui/camera_shutter.ogg:system/media/audio/ui/camera_shutter.ogg \
	vendor/amitwh/common/system/media/audio/ui/camera_focus.ogg:system/media/audio/ui/camera_focus.ogg \
	vendor/amitwh/common/system/media/audio/ui/NFCTransferComplete.ogg:system/media/audio/ui/NFCTransferComplete.ogg \
	vendor/amitwh/common/system/media/audio/ui/KeypressSpacebar.ogg:system/media/audio/ui/KeypressSpacebar.ogg \
	vendor/amitwh/common/system/media/audio/ui/NFCFailure.ogg:system/media/audio/ui/NFCFailure.ogg \
	vendor/amitwh/common/system/media/audio/ui/charge.ogg:system/media/audio/ui/charge.ogg \
	vendor/amitwh/common/system/media/audio/ui/Undock.ogg:system/media/audio/ui/Undock.ogg \
	vendor/amitwh/common/system/media/audio/notifications/FadeOut.ogg:system/media/audio/notifications/FadeOut.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Salacia.ogg:system/media/audio/notifications/Salacia.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Bulb.ogg:system/media/audio/notifications/Bulb.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Harp.ogg:system/media/audio/notifications/Harp.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Alert.ogg:system/media/audio/notifications/Alert.ogg \
	vendor/amitwh/common/system/media/audio/notifications/DingDong.ogg:system/media/audio/notifications/DingDong.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Clank.ogg:system/media/audio/notifications/Clank.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Shaula.ogg:system/media/audio/notifications/Shaula.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Piano.ogg:system/media/audio/notifications/Piano.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Sync.ogg:system/media/audio/notifications/Sync.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Europa.ogg:system/media/audio/notifications/Europa.ogg \
	vendor/amitwh/common/system/media/audio/notifications/KzurbSonar.ogg:system/media/audio/notifications/KzurbSonar.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Momentum.ogg:system/media/audio/notifications/Momentum.ogg \
	vendor/amitwh/common/system/media/audio/notifications/F1_New_MMS.ogg:system/media/audio/notifications/F1_New_MMS.ogg \
	vendor/amitwh/common/system/media/audio/notifications/NewBorn.ogg:system/media/audio/notifications/NewBorn.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Dudu.ogg:system/media/audio/notifications/Dudu.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Heaven_Nearby.ogg:system/media/audio/notifications/Heaven_Nearby.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Tumbler.ogg:system/media/audio/notifications/Tumbler.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Blip.ogg:system/media/audio/notifications/Blip.ogg \
	vendor/amitwh/common/system/media/audio/notifications/TaDa.ogg:system/media/audio/notifications/TaDa.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Stable.ogg:system/media/audio/notifications/Stable.ogg \
	vendor/amitwh/common/system/media/audio/notifications/S_Temple_bell.ogg:system/media/audio/notifications/S_Temple_bell.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Aldebaran.ogg:system/media/audio/notifications/Aldebaran.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Capella.ogg:system/media/audio/notifications/Capella.ogg \
	vendor/amitwh/common/system/media/audio/notifications/AttractiveSms.mp3:system/media/audio/notifications/AttractiveSms.mp3 \
	vendor/amitwh/common/system/media/audio/notifications/S_Whistle.ogg:system/media/audio/notifications/S_Whistle.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Frog.ogg:system/media/audio/notifications/Frog.ogg \
	vendor/amitwh/common/system/media/audio/notifications/message4.mp3:system/media/audio/notifications/message4.mp3 \
	vendor/amitwh/common/system/media/audio/notifications/Organic.ogg:system/media/audio/notifications/Organic.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Orders_up.ogg:system/media/audio/notifications/Orders_up.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Iridium.ogg:system/media/audio/notifications/Iridium.ogg \
	vendor/amitwh/common/system/media/audio/notifications/message3.mp3:system/media/audio/notifications/message3.mp3 \
	vendor/amitwh/common/system/media/audio/notifications/DialingMax.mp3:system/media/audio/notifications/DialingMax.mp3 \
	vendor/amitwh/common/system/media/audio/notifications/Burst.ogg:system/media/audio/notifications/Burst.ogg \
	vendor/amitwh/common/system/media/audio/notifications/CloudMagic_1.ogg:system/media/audio/notifications/CloudMagic_1.ogg \
	vendor/amitwh/common/system/media/audio/notifications/GoGo.ogg:system/media/audio/notifications/GoGo.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Mallet.ogg:system/media/audio/notifications/Mallet.ogg \
	vendor/amitwh/common/system/media/audio/notifications/S_Harmonics.ogg:system/media/audio/notifications/S_Harmonics.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Chime.ogg:system/media/audio/notifications/Chime.ogg \
	vendor/amitwh/common/system/media/audio/notifications/F1_MissedCall.ogg:system/media/audio/notifications/F1_MissedCall.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Elara.ogg:system/media/audio/notifications/Elara.ogg \
	vendor/amitwh/common/system/media/audio/notifications/S_Postman.ogg:system/media/audio/notifications/S_Postman.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Rubidium.ogg:system/media/audio/notifications/Rubidium.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Strontium.ogg:system/media/audio/notifications/Strontium.ogg \
	vendor/amitwh/common/system/media/audio/notifications/CaffeineSnake.ogg:system/media/audio/notifications/CaffeineSnake.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Xenon.ogg:system/media/audio/notifications/Xenon.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Selenium.ogg:system/media/audio/notifications/Selenium.ogg \
	vendor/amitwh/common/system/media/audio/notifications/S_Chirps.ogg:system/media/audio/notifications/S_Chirps.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Adara.ogg:system/media/audio/notifications/Adara.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Tethys.ogg:system/media/audio/notifications/Tethys.ogg \
	vendor/amitwh/common/system/media/audio/notifications/CrystalRing.ogg:system/media/audio/notifications/CrystalRing.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Shopkeeper.ogg:system/media/audio/notifications/Shopkeeper.ogg \
	vendor/amitwh/common/system/media/audio/notifications/S_Opener.ogg:system/media/audio/notifications/S_Opener.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Flying.ogg:system/media/audio/notifications/Flying.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Life.ogg:system/media/audio/notifications/Life.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Delight.ogg:system/media/audio/notifications/Delight.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Doink.ogg:system/media/audio/notifications/Doink.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Beginning.ogg:system/media/audio/notifications/Beginning.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Echoes.ogg:system/media/audio/notifications/Echoes.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Carme.ogg:system/media/audio/notifications/Carme.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Bloom.ogg:system/media/audio/notifications/Bloom.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Howl.ogg:system/media/audio/notifications/Howl.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Ariel.ogg:system/media/audio/notifications/Ariel.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Rhea.ogg:system/media/audio/notifications/Rhea.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Gentle_gong.ogg:system/media/audio/notifications/Gentle_gong.ogg \
	vendor/amitwh/common/system/media/audio/notifications/BaBa.ogg:system/media/audio/notifications/BaBa.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Quietly.ogg:system/media/audio/notifications/Quietly.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Cricket.ogg:system/media/audio/notifications/Cricket.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Ping.ogg:system/media/audio/notifications/Ping.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Palladium.ogg:system/media/audio/notifications/Palladium.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Ring.ogg:system/media/audio/notifications/Ring.ogg \
	vendor/amitwh/common/system/media/audio/notifications/SpaceSeed.ogg:system/media/audio/notifications/SpaceSeed.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Duet.ogg:system/media/audio/notifications/Duet.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Gallium.ogg:system/media/audio/notifications/Gallium.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Twinkle.ogg:system/media/audio/notifications/Twinkle.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Betelgeuse.ogg:system/media/audio/notifications/Betelgeuse.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Tejat.ogg:system/media/audio/notifications/Tejat.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Marbles.ogg:system/media/audio/notifications/Marbles.ogg \
	vendor/amitwh/common/system/media/audio/notifications/BlowBubble.ogg:system/media/audio/notifications/BlowBubble.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Pipes.ogg:system/media/audio/notifications/Pipes.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Procyon.ogg:system/media/audio/notifications/Procyon.ogg \
	vendor/amitwh/common/system/media/audio/notifications/MidTempoFunk.mp3:system/media/audio/notifications/MidTempoFunk.mp3 \
	vendor/amitwh/common/system/media/audio/notifications/S_Good_News.ogg:system/media/audio/notifications/S_Good_News.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Arcturus.ogg:system/media/audio/notifications/Arcturus.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Alya.ogg:system/media/audio/notifications/Alya.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Thallium.ogg:system/media/audio/notifications/Thallium.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Desire.ogg:system/media/audio/notifications/Desire.ogg \
	vendor/amitwh/common/system/media/audio/notifications/DontPanic.ogg:system/media/audio/notifications/DontPanic.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Jump.ogg:system/media/audio/notifications/Jump.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Bellatrix.ogg:system/media/audio/notifications/Bellatrix.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Altair.ogg:system/media/audio/notifications/Altair.ogg \
	vendor/amitwh/common/system/media/audio/notifications/S_Charming_bell.ogg:system/media/audio/notifications/S_Charming_bell.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Ceres.ogg:system/media/audio/notifications/Ceres.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Castor.ogg:system/media/audio/notifications/Castor.ogg \
	vendor/amitwh/common/system/media/audio/notifications/message5.mp3:system/media/audio/notifications/message5.mp3 \
	vendor/amitwh/common/system/media/audio/notifications/Spica.ogg:system/media/audio/notifications/Spica.ogg \
	vendor/amitwh/common/system/media/audio/notifications/S_Knock.ogg:system/media/audio/notifications/S_Knock.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Upsilon.ogg:system/media/audio/notifications/Upsilon.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Sticks_and_stones.ogg:system/media/audio/notifications/Sticks_and_stones.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Coconuts.ogg:system/media/audio/notifications/Coconuts.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Element.ogg:system/media/audio/notifications/Element.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Tweeter.ogg:system/media/audio/notifications/Tweeter.ogg \
	vendor/amitwh/common/system/media/audio/notifications/OnTheHunt.ogg:system/media/audio/notifications/OnTheHunt.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Talitha.ogg:system/media/audio/notifications/Talitha.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Sirrah.ogg:system/media/audio/notifications/Sirrah.ogg \
	vendor/amitwh/common/system/media/audio/notifications/vega.ogg:system/media/audio/notifications/vega.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Bird.ogg:system/media/audio/notifications/Bird.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Epic_Sines.ogg:system/media/audio/notifications/Epic_Sines.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Modular.ogg:system/media/audio/notifications/Modular.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Brush.ogg:system/media/audio/notifications/Brush.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Mira.ogg:system/media/audio/notifications/Mira.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Soft.ogg:system/media/audio/notifications/Soft.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Searchlight.ogg:system/media/audio/notifications/Searchlight.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Bright.ogg:system/media/audio/notifications/Bright.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Hello.ogg:system/media/audio/notifications/Hello.ogg \
	vendor/amitwh/common/system/media/audio/notifications/S_Bubbles.ogg:system/media/audio/notifications/S_Bubbles.ogg \
	vendor/amitwh/common/system/media/audio/notifications/FadeIn.ogg:system/media/audio/notifications/FadeIn.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Radon.ogg:system/media/audio/notifications/Radon.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Plastic_Pipe.ogg:system/media/audio/notifications/Plastic_Pipe.ogg \
	vendor/amitwh/common/system/media/audio/notifications/S_Pure_Bell.ogg:system/media/audio/notifications/S_Pure_Bell.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Msgtone.mp3:system/media/audio/notifications/Msgtone.mp3 \
	vendor/amitwh/common/system/media/audio/notifications/OpenArms.mp3:system/media/audio/notifications/OpenArms.mp3 \
	vendor/amitwh/common/system/media/audio/notifications/S_Flowers.ogg:system/media/audio/notifications/S_Flowers.ogg \
	vendor/amitwh/common/system/media/audio/notifications/pixiedust.ogg:system/media/audio/notifications/pixiedust.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Zirconium.ogg:system/media/audio/notifications/Zirconium.ogg \
	vendor/amitwh/common/system/media/audio/notifications/FleetingTime.ogg:system/media/audio/notifications/FleetingTime.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Spring.ogg:system/media/audio/notifications/Spring.ogg \
	vendor/amitwh/common/system/media/audio/notifications/moonbeam.ogg:system/media/audio/notifications/moonbeam.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Heaven.ogg:system/media/audio/notifications/Heaven.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Look.ogg:system/media/audio/notifications/Look.ogg \
	vendor/amitwh/common/system/media/audio/notifications/FoodBell.ogg:system/media/audio/notifications/FoodBell.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Pluck.ogg:system/media/audio/notifications/Pluck.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Antares.ogg:system/media/audio/notifications/Antares.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Antimony.ogg:system/media/audio/notifications/Antimony.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Bump.ogg:system/media/audio/notifications/Bump.ogg \
	vendor/amitwh/common/system/media/audio/notifications/ThoseWereTheDays.mp3:system/media/audio/notifications/ThoseWereTheDays.mp3 \
	vendor/amitwh/common/system/media/audio/notifications/OpenBottle.ogg:system/media/audio/notifications/OpenBottle.ogg \
	vendor/amitwh/common/system/media/audio/notifications/pizzicato.ogg:system/media/audio/notifications/pizzicato.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Intriguing.ogg:system/media/audio/notifications/Intriguing.ogg \
	vendor/amitwh/common/system/media/audio/notifications/LatinoTarintino.mp3:system/media/audio/notifications/LatinoTarintino.mp3 \
	vendor/amitwh/common/system/media/audio/notifications/message6.mp3:system/media/audio/notifications/message6.mp3 \
	vendor/amitwh/common/system/media/audio/notifications/Guitar.ogg:system/media/audio/notifications/Guitar.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Drip.ogg:system/media/audio/notifications/Drip.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Telly.ogg:system/media/audio/notifications/Telly.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Strange.ogg:system/media/audio/notifications/Strange.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Knock.ogg:system/media/audio/notifications/Knock.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Lalande.ogg:system/media/audio/notifications/Lalande.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Flutey_Water.ogg:system/media/audio/notifications/Flutey_Water.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Flute.ogg:system/media/audio/notifications/Flute.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Natural.ogg:system/media/audio/notifications/Natural.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Highwire.ogg:system/media/audio/notifications/Highwire.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Success.ogg:system/media/audio/notifications/Success.ogg \
	vendor/amitwh/common/system/media/audio/notifications/End_note.ogg:system/media/audio/notifications/End_note.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Tinkerbell.ogg:system/media/audio/notifications/Tinkerbell.ogg \
	vendor/amitwh/common/system/media/audio/notifications/NewSign.ogg:system/media/audio/notifications/NewSign.ogg \
	vendor/amitwh/common/system/media/audio/notifications/CrystalPiano.ogg:system/media/audio/notifications/CrystalPiano.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Whistle.ogg:system/media/audio/notifications/Whistle.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Prompt.ogg:system/media/audio/notifications/Prompt.ogg \
	vendor/amitwh/common/system/media/audio/notifications/S_Tickety_tock.ogg:system/media/audio/notifications/S_Tickety_tock.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Fluorine.ogg:system/media/audio/notifications/Fluorine.ogg \
	vendor/amitwh/common/system/media/audio/notifications/CetiAlpha.ogg:system/media/audio/notifications/CetiAlpha.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Voila.ogg:system/media/audio/notifications/Voila.ogg \
	vendor/amitwh/common/system/media/audio/notifications/GatedEuro.mp3:system/media/audio/notifications/GatedEuro.mp3 \
	vendor/amitwh/common/system/media/audio/notifications/Du.ogg:system/media/audio/notifications/Du.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Unfold.ogg:system/media/audio/notifications/Unfold.ogg \
	vendor/amitwh/common/system/media/audio/notifications/regulus.ogg:system/media/audio/notifications/regulus.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Iapetus.ogg:system/media/audio/notifications/Iapetus.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Moto.ogg:system/media/audio/notifications/Moto.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Tone_Doorbell.mp3:system/media/audio/notifications/Tone_Doorbell.mp3 \
	vendor/amitwh/common/system/media/audio/notifications/Dreaming.mp3:system/media/audio/notifications/Dreaming.mp3 \
	vendor/amitwh/common/system/media/audio/notifications/DeskBell.mp3:system/media/audio/notifications/DeskBell.mp3 \
	vendor/amitwh/common/system/media/audio/notifications/message1.mp3:system/media/audio/notifications/message1.mp3 \
	vendor/amitwh/common/system/media/audio/notifications/Bubble.ogg:system/media/audio/notifications/Bubble.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Di.ogg:system/media/audio/notifications/Di.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Flowering.ogg:system/media/audio/notifications/Flowering.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Doors.ogg:system/media/audio/notifications/Doors.ogg \
	vendor/amitwh/common/system/media/audio/notifications/S_Dew_drops.ogg:system/media/audio/notifications/S_Dew_drops.ogg \
	vendor/amitwh/common/system/media/audio/notifications/message8.mp3:system/media/audio/notifications/message8.mp3 \
	vendor/amitwh/common/system/media/audio/notifications/CountryGuitar.ogg:system/media/audio/notifications/CountryGuitar.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Krypton.ogg:system/media/audio/notifications/Krypton.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Polaris.ogg:system/media/audio/notifications/Polaris.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Simple.ogg:system/media/audio/notifications/Simple.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Talk.ogg:system/media/audio/notifications/Talk.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Popcorn.ogg:system/media/audio/notifications/Popcorn.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Cobalt.ogg:system/media/audio/notifications/Cobalt.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Titan.ogg:system/media/audio/notifications/Titan.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Fluting.ogg:system/media/audio/notifications/Fluting.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Mouse.ogg:system/media/audio/notifications/Mouse.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Bottle.ogg:system/media/audio/notifications/Bottle.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Proxima.ogg:system/media/audio/notifications/Proxima.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Fomalhaut.ogg:system/media/audio/notifications/Fomalhaut.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Hit.ogg:system/media/audio/notifications/Hit.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Pollux.ogg:system/media/audio/notifications/Pollux.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Chirp.ogg:system/media/audio/notifications/Chirp.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Deneb.ogg:system/media/audio/notifications/Deneb.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Tuneup.ogg:system/media/audio/notifications/Tuneup.ogg \
	vendor/amitwh/common/system/media/audio/notifications/TangoInLove.mp3:system/media/audio/notifications/TangoInLove.mp3 \
	vendor/amitwh/common/system/media/audio/notifications/Electra.ogg:system/media/audio/notifications/Electra.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Fresh.ogg:system/media/audio/notifications/Fresh.ogg \
	vendor/amitwh/common/system/media/audio/notifications/DearDeer.ogg:system/media/audio/notifications/DearDeer.ogg \
	vendor/amitwh/common/system/media/audio/notifications/FunkyArabia.mp3:system/media/audio/notifications/FunkyArabia.mp3 \
	vendor/amitwh/common/system/media/audio/notifications/Hojus.ogg:system/media/audio/notifications/Hojus.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Light.ogg:system/media/audio/notifications/Light.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Mystery.ogg:system/media/audio/notifications/Mystery.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Beat_Box_Android.ogg:system/media/audio/notifications/Beat_Box_Android.ogg \
	vendor/amitwh/common/system/media/audio/notifications/message7.mp3:system/media/audio/notifications/message7.mp3 \
	vendor/amitwh/common/system/media/audio/notifications/AGT.ogg:system/media/audio/notifications/AGT.ogg \
	vendor/amitwh/common/system/media/audio/notifications/sirius.ogg:system/media/audio/notifications/sirius.ogg \
	vendor/amitwh/common/system/media/audio/notifications/F1_New_SMS.ogg:system/media/audio/notifications/F1_New_SMS.ogg \
	vendor/amitwh/common/system/media/audio/notifications/message2.mp3:system/media/audio/notifications/message2.mp3 \
	vendor/amitwh/common/system/media/audio/notifications/Clear.ogg:system/media/audio/notifications/Clear.ogg \
	vendor/amitwh/common/system/media/audio/notifications/S_On_time.ogg:system/media/audio/notifications/S_On_time.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Argon.ogg:system/media/audio/notifications/Argon.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Beryllium.ogg:system/media/audio/notifications/Beryllium.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Syrma.ogg:system/media/audio/notifications/Syrma.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Blink.ogg:system/media/audio/notifications/Blink.ogg \
	vendor/amitwh/common/system/media/audio/notifications/MagicalDrug.ogg:system/media/audio/notifications/MagicalDrug.ogg \
	vendor/amitwh/common/system/media/audio/notifications/ElectronBeam.ogg:system/media/audio/notifications/ElectronBeam.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Merope.ogg:system/media/audio/notifications/Merope.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Secret.ogg:system/media/audio/notifications/Secret.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Grunting.ogg:system/media/audio/notifications/Grunting.ogg \
	vendor/amitwh/common/system/media/audio/notifications/tweeters.ogg:system/media/audio/notifications/tweeters.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Single_Clang.ogg:system/media/audio/notifications/Single_Clang.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Ivory.ogg:system/media/audio/notifications/Ivory.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Curiosity.ogg:system/media/audio/notifications/Curiosity.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Helium.ogg:system/media/audio/notifications/Helium.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Signal.ogg:system/media/audio/notifications/Signal.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Echo.ogg:system/media/audio/notifications/Echo.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Notice.ogg:system/media/audio/notifications/Notice.ogg \
	vendor/amitwh/common/system/media/audio/notifications/Canopus.ogg:system/media/audio/notifications/Canopus.ogg \
	vendor/amitwh/common/system/media/audio/alarms/GoodMorning.ogg:system/media/audio/alarms/GoodMorning.ogg \
	vendor/amitwh/common/system/media/audio/alarms/MorningSun.ogg:system/media/audio/alarms/MorningSun.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Awakening.ogg:system/media/audio/alarms/Awakening.ogg \
	vendor/amitwh/common/system/media/audio/alarms/New_Morning.ogg:system/media/audio/alarms/New_Morning.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Hurry.ogg:system/media/audio/alarms/Hurry.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Dreams.ogg:system/media/audio/alarms/Dreams.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Ding.ogg:system/media/audio/alarms/Ding.ogg \
	vendor/amitwh/common/system/media/audio/alarms/ringtong10.mp3:system/media/audio/alarms/ringtong10.mp3 \
	vendor/amitwh/common/system/media/audio/alarms/Plutonium.ogg:system/media/audio/alarms/Plutonium.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Sky.ogg:system/media/audio/alarms/Sky.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Jump_start.ogg:system/media/audio/alarms/Jump_start.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Twirling_In_Time.ogg:system/media/audio/alarms/Twirling_In_Time.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Sunrise.ogg:system/media/audio/alarms/Sunrise.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Cesium.ogg:system/media/audio/alarms/Cesium.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Memory_World.ogg:system/media/audio/alarms/Memory_World.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Respire.ogg:system/media/audio/alarms/Respire.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Lullaby.ogg:system/media/audio/alarms/Lullaby.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Loose_change.ogg:system/media/audio/alarms/Loose_change.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Aesthete.ogg:system/media/audio/alarms/Aesthete.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Atlas.ogg:system/media/audio/alarms/Atlas.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Tribal.ogg:system/media/audio/alarms/Tribal.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Happy.ogg:system/media/audio/alarms/Happy.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Atria.ogg:system/media/audio/alarms/Atria.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Potpourri.ogg:system/media/audio/alarms/Potpourri.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Lux.ogg:system/media/audio/alarms/Lux.ogg \
	vendor/amitwh/common/system/media/audio/alarms/EtherealMallets.ogg:system/media/audio/alarms/EtherealMallets.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Rolling_fog.ogg:system/media/audio/alarms/Rolling_fog.ogg \
	vendor/amitwh/common/system/media/audio/alarms/AlarmClock2.mp3:system/media/audio/alarms/AlarmClock2.mp3 \
	vendor/amitwh/common/system/media/audio/alarms/Inception.ogg:system/media/audio/alarms/Inception.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Cuckoo_clock.ogg:system/media/audio/alarms/Cuckoo_clock.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Platinum.ogg:system/media/audio/alarms/Platinum.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Dalia.ogg:system/media/audio/alarms/Dalia.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Fermium.ogg:system/media/audio/alarms/Fermium.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Awoken.ogg:system/media/audio/alarms/Awoken.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Primus.ogg:system/media/audio/alarms/Primus.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Alarm_Beep_02.ogg:system/media/audio/alarms/Alarm_Beep_02.ogg \
	vendor/amitwh/common/system/media/audio/alarms/GentleNight.ogg:system/media/audio/alarms/GentleNight.ogg \
	vendor/amitwh/common/system/media/audio/alarms/WakeUpWakeUp.mp3:system/media/audio/alarms/WakeUpWakeUp.mp3 \
	vendor/amitwh/common/system/media/audio/alarms/SunshineForest.ogg:system/media/audio/alarms/SunshineForest.ogg \
	vendor/amitwh/common/system/media/audio/alarms/ClockBird.ogg:system/media/audio/alarms/ClockBird.ogg \
	vendor/amitwh/common/system/media/audio/alarms/SummerDay.ogg:system/media/audio/alarms/SummerDay.ogg \
	vendor/amitwh/common/system/media/audio/alarms/ringtong9.mp3:system/media/audio/alarms/ringtong9.mp3 \
	vendor/amitwh/common/system/media/audio/alarms/ringtong6.mp3:system/media/audio/alarms/ringtong6.mp3 \
	vendor/amitwh/common/system/media/audio/alarms/Vega.ogg:system/media/audio/alarms/Vega.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Spica.ogg:system/media/audio/alarms/Spica.ogg \
	vendor/amitwh/common/system/media/audio/alarms/MorningSunShine.ogg:system/media/audio/alarms/MorningSunShine.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Beep.ogg:system/media/audio/alarms/Beep.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Alarm_Beep_03.ogg:system/media/audio/alarms/Alarm_Beep_03.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Live.ogg:system/media/audio/alarms/Live.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Walk_in_the_forest.ogg:system/media/audio/alarms/Walk_in_the_forest.ogg \
	vendor/amitwh/common/system/media/audio/alarms/MorningBird.ogg:system/media/audio/alarms/MorningBird.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Timing.ogg:system/media/audio/alarms/Timing.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Avior.ogg:system/media/audio/alarms/Avior.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Spring.ogg:system/media/audio/alarms/Spring.ogg \
	vendor/amitwh/common/system/media/audio/alarms/PastTime.ogg:system/media/audio/alarms/PastTime.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Dolphin.ogg:system/media/audio/alarms/Dolphin.ogg \
	vendor/amitwh/common/system/media/audio/alarms/A_real_hoot.ogg:system/media/audio/alarms/A_real_hoot.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Gentle_breeze.ogg:system/media/audio/alarms/Gentle_breeze.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Early_twilight.ogg:system/media/audio/alarms/Early_twilight.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Windmill.ogg:system/media/audio/alarms/Windmill.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Early_Morning.ogg:system/media/audio/alarms/Early_Morning.ogg \
	vendor/amitwh/common/system/media/audio/alarms/TickTack.ogg:system/media/audio/alarms/TickTack.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Hassium.ogg:system/media/audio/alarms/Hassium.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Carina.ogg:system/media/audio/alarms/Carina.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Spokes.ogg:system/media/audio/alarms/Spokes.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Alarm_Buzzer.ogg:system/media/audio/alarms/Alarm_Buzzer.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Lyra.ogg:system/media/audio/alarms/Lyra.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Rooster.ogg:system/media/audio/alarms/Rooster.ogg \
	vendor/amitwh/common/system/media/audio/alarms/AngelsHarp.ogg:system/media/audio/alarms/AngelsHarp.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Full_of_wonder.ogg:system/media/audio/alarms/Full_of_wonder.ogg \
	vendor/amitwh/common/system/media/audio/alarms/GetUp.ogg:system/media/audio/alarms/GetUp.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Alarm_Beep_01.ogg:system/media/audio/alarms/Alarm_Beep_01.ogg \
	vendor/amitwh/common/system/media/audio/alarms/GoodLuck.ogg:system/media/audio/alarms/GoodLuck.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Daydream.ogg:system/media/audio/alarms/Daydream.ogg \
	vendor/amitwh/common/system/media/audio/alarms/ClassicAlarm.ogg:system/media/audio/alarms/ClassicAlarm.ogg \
	vendor/amitwh/common/system/media/audio/alarms/HappyMorning.ogg:system/media/audio/alarms/HappyMorning.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Crescendo.ogg:system/media/audio/alarms/Crescendo.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Meadow.ogg:system/media/audio/alarms/Meadow.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Sunshower.ogg:system/media/audio/alarms/Sunshower.ogg \
	vendor/amitwh/common/system/media/audio/alarms/DeepOcean.ogg:system/media/audio/alarms/DeepOcean.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Church.ogg:system/media/audio/alarms/Church.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Lanx.ogg:system/media/audio/alarms/Lanx.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Alarm_Rooster_02.ogg:system/media/audio/alarms/Alarm_Rooster_02.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Playful.ogg:system/media/audio/alarms/Playful.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Argon.ogg:system/media/audio/alarms/Argon.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Virgo.ogg:system/media/audio/alarms/Virgo.ogg \
	vendor/amitwh/common/system/media/audio/alarms/GoodNewDay.ogg:system/media/audio/alarms/GoodNewDay.ogg \
	vendor/amitwh/common/system/media/audio/alarms/Bright_morning.ogg:system/media/audio/alarms/Bright_morning.ogg \
	vendor/amitwh/common/system/media/audio/alarms/RoosterRumble.mp3:system/media/audio/alarms/RoosterRumble.mp3 \
	vendor/amitwh/common/system/media/audio/alarms/Icicles.ogg:system/media/audio/alarms/Icicles.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Lost_and_found.ogg:system/media/audio/ringtones/Lost_and_found.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/GuitarPop.ogg:system/media/audio/ringtones/GuitarPop.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Ring_Digital_02.ogg:system/media/audio/ringtones/Ring_Digital_02.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Girtab.ogg:system/media/audio/ringtones/Girtab.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Blinking.ogg:system/media/audio/ringtones/Blinking.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/MaLing.ogg:system/media/audio/ringtones/MaLing.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Song_Of_Rain.ogg:system/media/audio/ringtones/Song_Of_Rain.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/DoDaDa.ogg:system/media/audio/ringtones/DoDaDa.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Water_World.ogg:system/media/audio/ringtones/Water_World.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/BrandFusion.mp3:system/media/audio/ringtones/BrandFusion.mp3 \
	vendor/amitwh/common/system/media/audio/ringtones/ToyRobot.ogg:system/media/audio/ringtones/ToyRobot.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Stars.ogg:system/media/audio/ringtones/Stars.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/07_Rain_drops.ogg:system/media/audio/ringtones/07_Rain_drops.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/HalfwayHome.ogg:system/media/audio/ringtones/HalfwayHome.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Momentum.ogg:system/media/audio/ringtones/Momentum.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Ring_Tone2.mp3:system/media/audio/ringtones/Ring_Tone2.mp3 \
	vendor/amitwh/common/system/media/audio/ringtones/Orion.ogg:system/media/audio/ringtones/Orion.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/13_Midnight_picnic.ogg:system/media/audio/ringtones/13_Midnight_picnic.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/MiGlassChime.ogg:system/media/audio/ringtones/MiGlassChime.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/MidEvilJaunt.ogg:system/media/audio/ringtones/MidEvilJaunt.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Luna.ogg:system/media/audio/ringtones/Luna.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/TribalLanguage.ogg:system/media/audio/ringtones/TribalLanguage.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/LullabyPiano.ogg:system/media/audio/ringtones/LullabyPiano.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Scarabaeus.ogg:system/media/audio/ringtones/Scarabaeus.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Silence.ogg:system/media/audio/ringtones/Silence.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Raindrops.ogg:system/media/audio/ringtones/Raindrops.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Organic.ogg:system/media/audio/ringtones/Organic.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Church_Spirit.ogg:system/media/audio/ringtones/Church_Spirit.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Keys.ogg:system/media/audio/ringtones/Keys.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/16_High_tide.ogg:system/media/audio/ringtones/16_High_tide.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/BellBell.ogg:system/media/audio/ringtones/BellBell.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/The_big_adventure.ogg:system/media/audio/ringtones/The_big_adventure.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Doll.ogg:system/media/audio/ringtones/Doll.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Zen_too.ogg:system/media/audio/ringtones/Zen_too.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/CoolLead.ogg:system/media/audio/ringtones/CoolLead.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Mash_up.ogg:system/media/audio/ringtones/Mash_up.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Schools_out.ogg:system/media/audio/ringtones/Schools_out.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/ZUK_Goldentime.ogg:system/media/audio/ringtones/ZUK_Goldentime.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Orange.ogg:system/media/audio/ringtones/Orange.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/08_Moonlit_beach.ogg:system/media/audio/ringtones/08_Moonlit_beach.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/SpaceBird.ogg:system/media/audio/ringtones/SpaceBird.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Hotline.ogg:system/media/audio/ringtones/Hotline.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Krystaline.ogg:system/media/audio/ringtones/Krystaline.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/ZUK_Girls.ogg:system/media/audio/ringtones/ZUK_Girls.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/EtherShake.ogg:system/media/audio/ringtones/EtherShake.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Aquila.ogg:system/media/audio/ringtones/Aquila.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/MusicBox.ogg:system/media/audio/ringtones/MusicBox.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/MiMix.ogg:system/media/audio/ringtones/MiMix.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Hexagon.ogg:system/media/audio/ringtones/Hexagon.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/14_Drifting_downstream.ogg:system/media/audio/ringtones/14_Drifting_downstream.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Complex.ogg:system/media/audio/ringtones/Complex.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Game.ogg:system/media/audio/ringtones/Game.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Themos.ogg:system/media/audio/ringtones/Themos.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Charmed_Life.ogg:system/media/audio/ringtones/Charmed_Life.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/MiClassic.ogg:system/media/audio/ringtones/MiClassic.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Vespa.ogg:system/media/audio/ringtones/Vespa.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Home.ogg:system/media/audio/ringtones/Home.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Lollipop.ogg:system/media/audio/ringtones/Lollipop.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Naughty.ogg:system/media/audio/ringtones/Naughty.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/LeisureTime.ogg:system/media/audio/ringtones/LeisureTime.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Callisto.ogg:system/media/audio/ringtones/Callisto.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Jump.ogg:system/media/audio/ringtones/Jump.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/SecretGarden.ogg:system/media/audio/ringtones/SecretGarden.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/ringtong9.mp3:system/media/audio/ringtones/ringtong9.mp3 \
	vendor/amitwh/common/system/media/audio/ringtones/ringtong6.mp3:system/media/audio/ringtones/ringtong6.mp3 \
	vendor/amitwh/common/system/media/audio/ringtones/ZUK_Elves.ogg:system/media/audio/ringtones/ZUK_Elves.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Rigel.ogg:system/media/audio/ringtones/Rigel.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/80s.ogg:system/media/audio/ringtones/80s.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/29_Gentle_spring_rain.ogg:system/media/audio/ringtones/29_Gentle_spring_rain.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/10_Mountain_temple.ogg:system/media/audio/ringtones/10_Mountain_temple.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Ring_Synth_02.ogg:system/media/audio/ringtones/Ring_Synth_02.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/GuitarRetro.ogg:system/media/audio/ringtones/GuitarRetro.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/SitarVsSitar.ogg:system/media/audio/ringtones/SitarVsSitar.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/GameOverGuitar.ogg:system/media/audio/ringtones/GameOverGuitar.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Incoming.ogg:system/media/audio/ringtones/Incoming.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Triton.ogg:system/media/audio/ringtones/Triton.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/RobotsforEveryone.ogg:system/media/audio/ringtones/RobotsforEveryone.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Playa.ogg:system/media/audio/ringtones/Playa.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/ZUK_GoldentimeVL.ogg:system/media/audio/ringtones/ZUK_GoldentimeVL.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/MorningSunshine.ogg:system/media/audio/ringtones/MorningSunshine.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Awake.ogg:system/media/audio/ringtones/Awake.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/28_Fairy_fountain.ogg:system/media/audio/ringtones/28_Fairy_fountain.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/GuitarClassic.ogg:system/media/audio/ringtones/GuitarClassic.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/02_Fog_on_the_water.ogg:system/media/audio/ringtones/02_Fog_on_the_water.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Hello.ogg:system/media/audio/ringtones/Hello.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/DreamingMax.mp3:system/media/audio/ringtones/DreamingMax.mp3 \
	vendor/amitwh/common/system/media/audio/ringtones/DalaGuitar.ogg:system/media/audio/ringtones/DalaGuitar.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Childhood.ogg:system/media/audio/ringtones/Childhood.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Ringtone_3.mp3:system/media/audio/ringtones/Ringtone_3.mp3 \
	vendor/amitwh/common/system/media/audio/ringtones/Hover_Laterally.ogg:system/media/audio/ringtones/Hover_Laterally.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Feel_Lucky.ogg:system/media/audio/ringtones/Feel_Lucky.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/MorningBreeze.ogg:system/media/audio/ringtones/MorningBreeze.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Memory.ogg:system/media/audio/ringtones/Memory.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Ring_Classic_02.ogg:system/media/audio/ringtones/Ring_Classic_02.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Gimme_Mo_Town.ogg:system/media/audio/ringtones/Gimme_Mo_Town.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Aurora.ogg:system/media/audio/ringtones/Aurora.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Jocosity.ogg:system/media/audio/ringtones/Jocosity.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/DingDang.ogg:system/media/audio/ringtones/DingDang.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/ZUK_RainbowSweet.ogg:system/media/audio/ringtones/ZUK_RainbowSweet.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Strings.ogg:system/media/audio/ringtones/Strings.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Ganymede.ogg:system/media/audio/ringtones/Ganymede.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Natural.ogg:system/media/audio/ringtones/Natural.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/09_Underwater_world.ogg:system/media/audio/ringtones/09_Underwater_world.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Flutterby.ogg:system/media/audio/ringtones/Flutterby.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Freedom.ogg:system/media/audio/ringtones/Freedom.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/ClassicalPiano.ogg:system/media/audio/ringtones/ClassicalPiano.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Machina.ogg:system/media/audio/ringtones/Machina.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Work.ogg:system/media/audio/ringtones/Work.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/DXOrange.ogg:system/media/audio/ringtones/DXOrange.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Leaps_and_bounds.ogg:system/media/audio/ringtones/Leaps_and_bounds.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/FreeFlight.ogg:system/media/audio/ringtones/FreeFlight.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Elegant.ogg:system/media/audio/ringtones/Elegant.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/MI.ogg:system/media/audio/ringtones/MI.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/PingPong.ogg:system/media/audio/ringtones/PingPong.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Ringtone_7.mp3:system/media/audio/ringtones/Ringtone_7.mp3 \
	vendor/amitwh/common/system/media/audio/ringtones/HelloBill.ogg:system/media/audio/ringtones/HelloBill.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/SunnyDay.ogg:system/media/audio/ringtones/SunnyDay.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Carina.ogg:system/media/audio/ringtones/Carina.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Carousel.ogg:system/media/audio/ringtones/Carousel.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Onward.ogg:system/media/audio/ringtones/Onward.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Simple.ogg:system/media/audio/ringtones/Simple.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/BrandIndianContemp.mp3:system/media/audio/ringtones/BrandIndianContemp.mp3 \
	vendor/amitwh/common/system/media/audio/ringtones/Thinker.ogg:system/media/audio/ringtones/Thinker.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Lyra.ogg:system/media/audio/ringtones/Lyra.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Umbriel.ogg:system/media/audio/ringtones/Umbriel.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/DonMessWivIt.ogg:system/media/audio/ringtones/DonMessWivIt.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Cheerful.ogg:system/media/audio/ringtones/Cheerful.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Pyxis.ogg:system/media/audio/ringtones/Pyxis.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Music.mp3:system/media/audio/ringtones/Music.mp3 \
	vendor/amitwh/common/system/media/audio/ringtones/Jete.ogg:system/media/audio/ringtones/Jete.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/MiXylophone.ogg:system/media/audio/ringtones/MiXylophone.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/FunkyGuitar.ogg:system/media/audio/ringtones/FunkyGuitar.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Titania.ogg:system/media/audio/ringtones/Titania.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Monkey_around.ogg:system/media/audio/ringtones/Monkey_around.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Funky.ogg:system/media/audio/ringtones/Funky.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/IceWorldPiano.ogg:system/media/audio/ringtones/IceWorldPiano.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/VLtime.ogg:system/media/audio/ringtones/VLtime.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Default.mp3:system/media/audio/ringtones/Default.mp3 \
	vendor/amitwh/common/system/media/audio/ringtones/Illusion.ogg:system/media/audio/ringtones/Illusion.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Ring_Synth_04.ogg:system/media/audio/ringtones/Ring_Synth_04.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Square_Drive.ogg:system/media/audio/ringtones/Square_Drive.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Copycat.ogg:system/media/audio/ringtones/Copycat.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Sedna.ogg:system/media/audio/ringtones/Sedna.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Glockenspiel.ogg:system/media/audio/ringtones/Glockenspiel.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/JoyfulJoy.ogg:system/media/audio/ringtones/JoyfulJoy.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/27_Sparkling_mist.ogg:system/media/audio/ringtones/27_Sparkling_mist.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/HappyTime.ogg:system/media/audio/ringtones/HappyTime.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Fantastic_Clang.ogg:system/media/audio/ringtones/Fantastic_Clang.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/25_The_secret_forest.ogg:system/media/audio/ringtones/25_The_secret_forest.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/DreamTheme.ogg:system/media/audio/ringtones/DreamTheme.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Rumba.ogg:system/media/audio/ringtones/Rumba.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Solarium.ogg:system/media/audio/ringtones/Solarium.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Enthusiastic.ogg:system/media/audio/ringtones/Enthusiastic.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/MorningStreamlet.ogg:system/media/audio/ringtones/MorningStreamlet.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Crackle.ogg:system/media/audio/ringtones/Crackle.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/ElectricBell.ogg:system/media/audio/ringtones/ElectricBell.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Phobos.ogg:system/media/audio/ringtones/Phobos.ogg \
	vendor/amitwh/common/system/media/audio/ringtones/Echo.ogg:system/media/audio/ringtones/Echo.ogg 
